[package]
name = "textkey-android-resource-generator"
version = "0.1.0"
authors = ["Oscar Nylander <oscar@hedvig.com>"]
edition = "2018"

[dependencies]
graphql_client = "0.6.1"
serde = "1.0.88"
serde_derive = "1.0.88"
reqwest = "0.9.10"
